insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Вратари', 1, 'Роберт Альмер', '20.03.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 2, 'Дьердь Гарич', '08.03.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Защитники', 3, 'Александар Драгович', '06.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Защитники', 4, 'Мартин Хинтереггер', '07.09.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Защитники', 5, 'Кристиан Фухс', '07.04.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 6, 'Штефан Инсалькер', '18.05.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Нападающие', 7, 'Марко Арнаутович', '19.04.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 8, 'Давид Алаба', '24.06.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Нападающие', 9, 'Рубен Окоти', '06.06.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 10, 'Златко Юнузович', '26.09.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 11, 'Мартин Харник', '10.06.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Вратари', 12, 'Хайнц Линднер', '17.07.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Защитники', 13, 'Маркус Зуттнер', '16.04.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 14, 'Юлиан Баумгартлингер', '02.01.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Защитники', 15, 'Себастьян Предль', '21.06.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Защитники', 16, 'Кевин Виммер', '15.11.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Защитники', 17, 'Флориан Кляйн', '17.11.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 18, 'Алессандро Шопф', '07.02.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Нападающие', 19, 'Лукас Хинтерзеер', '28.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 20, 'Марсель Забитцер', '17.03.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Нападающие', 21, 'Марк Янко', '25.06.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Полузащитники', 22, 'Якоб Янчер', '08.01.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('австрия', 'Вратари', 23, 'Рамазан Эзкан', '28.06.84');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Вратари', 1, 'Этрит Бериша', '10.03.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 2, 'Анди Лиля', '12.02.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 3, 'Эрмир Леняни', '05.08.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 4, 'Эльсейд Хюсай', '20.02.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 5, 'Лорик Цана', '27.07.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 6, 'Весели Весели', '20.11.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 7, 'Анси Аголи', '11.10.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Полузащитники', 8, 'Мигьен Баша', '05.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Полузащитники', 9, 'Ледиан Мемушай', '17.12.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Нападающие', 10, 'Армандо Садику', '27.05.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Нападающие', 11, 'Шкельзен Гаши', '15.07.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Вратари', 12, 'Оргес Шехи', '25.09.77');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Полузащитники', 13, 'Бурим Кукели', '16.01.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Полузащитники', 14, 'Таулянт Джака', '28.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 15, 'Мергим Маврай', '09.06.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Нападающие', 16, 'Соколь Чикалеши', '27.07.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 17, 'Насер Алийи', '27.12.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Защитники', 18, 'Арлинд Айети', '25.09.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Нападающие', 19, 'Беким Балай', '11.01.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Полузащитники', 20, 'Эргюс Каче', '08.07.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Полузащитники', 21, 'Одисе Роши', '22.05.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Полузащитники', 22, 'Амир Абраши', '27.03.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('албания', 'Вратари', 23, 'Альбан Ходжа', '23.11.87');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Вратари', 1, 'Джо Харт', '19.04.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Защитники', 2, 'Кайл Уокер', '28.05.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Защитники', 3, 'Дэнни Роуз', '02.07.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 4, 'Джеймс Милнер', '04.01.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Защитники', 5, 'Гэри Кэхилл', '19.12.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Защитники', 6, 'Крис Смоллинг', '22.11.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 7, 'Рахим Стерлинг', '08.12.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 8, 'Адам Лаллана', '10.05.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Нападающие', 9, 'Харри Кейн', '28.07.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Нападающие', 10, 'Уэйн Руни', '24.10.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Нападающие', 11, 'Джейми Варди', '11.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Защитники', 12, 'Натаниэл Клайн', '05.04.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Вратари', 13, 'Фрейзер Форстер', '17.03.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 14, 'Джордан Хендерсон', '17.06.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Нападающие', 15, 'Даниэл Старридж', '01.09.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Защитники', 16, 'Джон Стоунз', '28.05.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 17, 'Эрик Дайер', '15.01.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 18, 'Джек Уилшир', '01.01.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 19, 'Росс Баркли', '05.12.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Полузащитники', 20, 'Деле Алли', '11.04.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Защитники', 21, 'Райан Бертранд', '05.08.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Нападающие', 22, 'Маркус Рэшфорд', '31.10.97');
insert into t_player_buf(country, player_type, num, name, birthday) values('англия', 'Вратари', 23, 'Том Хитон', '15.04.86');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Вратари', 1, 'Тибо Куртуа', '11.05.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 2, 'Тоби Алдервейрелд', '02.03.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 3, 'Томас Вермален', '14.11.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Полузащитники', 4, 'Раджа Наингголан', '04.05.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 5, 'Ян Вертонген', '24.04.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Полузащитники', 6, 'Аксель Витсель', '12.01.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Полузащитники', 7, 'Кевин де Брeйне', '28.06.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Полузащитники', 8, 'Маруан Феллайни', '22.11.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Нападающие', 9, 'Ромелу Лукаку', '13.05.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Полузащитники', 10, 'Эден Азар', '07.01.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Полузащитники', 11, 'Янник Карраско', '04.09.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Вратари', 12, 'Симон Миньоле', '06.08.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Вратари', 13, 'Жан-Франсуа Жийе', '31.05.79');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Нападающие', 14, 'Дрис Мертенс', '06.05.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 15, 'Джейсон Денайе', '28.06.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 16, 'Томас Менье', '12.09.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Нападающие', 17, 'Дивок Ориги', '18.04.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 18, 'Кристиан Кабаселе', '24.02.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Полузащитники', 19, 'Мусса Дембеле', '16.07.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Нападающие', 20, 'Кристиан Бентеке', '03.12.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 21, 'Джордан Лукаку', '25.07.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Нападающие', 22, 'Миши Бачуайи', '02.10.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('бельгия', 'Защитники', 23, 'Лоран Симан', '05.08.85');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Вратари', 1, 'Габор Кирай', '01.04.76');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 2, 'Адам Лонг', '17.01.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 3, 'Михай Корхут', '01.12.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 4, 'Томаш Кадар', '14.03.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 5, 'Оттило Фиоло', '17.02.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Полузащитники', 6, 'Акош Элек', '21.07.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Полузащитники', 7, 'Балаж Джуджак', '23.12.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Полузащитники', 8, 'Адам Нодь', '17.06.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Нападающие', 9, 'Адам Солои', '09.12.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Полузащитники', 10, 'Золтан Геро', '22.04.79');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Нападающие', 11, 'Кристиан Немет', '05.01.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Вратари', 12, 'Денеш Дибус', '16.11.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Нападающие', 13, 'Даниэль Беде', '24.10.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Полузащитники', 14, 'Герге Ловренчич', '01.09.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Полузащитники', 15, 'Ласло Кляйнхайслер', '08.04.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 16, 'Адам Пинтер', '12.06.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Нападающие', 17, 'Неманья Николич', '31.12.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Полузащитники', 18, 'Золтан Штибер', '16.10.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Нападающие', 19, 'Томаш Пришкин', '27.09.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 20, 'Ричард Гузмич', '16.04.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 21, 'Борнобаш Беше', '06.05.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Вратари', 22, 'Петар Гулач', '06.05.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('венгрия', 'Защитники', 23, 'Роланд Юхас', '01.07.83');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Вратари', 1, 'Мануэль Нойер', '27.03.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Защитники', 2, 'Шкодран Мустафи', '17.04.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Защитники', 3, 'Йонас Хектор', '27.05.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Защитники', 4, 'Бенедикт Хеведес', '29.02.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Защитники', 5, 'Матс Хуммельс', '16.12.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 6, 'Сами Хедира', '04.04.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 7, 'Бастиан Шванштайгер', '01.08.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 8, 'Месут Озил', '15.10.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 9, 'Андре Шюррле', '06.11.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Нападающие', 10, 'Лукас Подольски', '04.06.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 11, 'Юлиан Дракслер', '20.09.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Вратари', 12, 'Бернд Лено', '04.03.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Нападающие', 13, 'Томас Мюллер', '13.09.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 14, 'Эмре Джан', '12.01.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 15, 'Юлиан Вайгль', '08.09.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Защитники', 16, 'Антонио Рюдигер', '03.03.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Защитники', 17, 'Жером Боатенг', '03.09.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 18, 'Тони Кроос', '04.01.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 19, 'Марио Гетце', '03.06.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Полузащитники', 20, 'Лерой Сане', '11.01.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Защитники', 21, 'Йосуа Киммих', '08.02.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Вратари', 22, 'Марк-Андре тер Стеген', '30.04.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('германия', 'Нападающие', 23, 'Марио Гомес', '10.07.85');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Вратари', 1, 'Кейрен Вествуд', '23.10.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Защитники', 2, 'Шимус Коулмен', '11.10.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Защитники', 3, 'Киран Кларк', '26.09.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Защитники', 4, 'Джон О''Ши', '30.04.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Защитники', 5, 'Ричард Киог', '11.08.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 6, 'Гленн Уилан', '13.01.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 7, 'Эйден Макгиди', '04.04.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 8, 'Джеймс Маккарти', '12.11.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Нападающие', 9, 'Шейн Лонг', '22.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Нападающие', 10, 'Робби Кин', '08.07.80');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 11, 'Джеймс Макклин', '22.04.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Защитники', 12, 'Шейн Даффи', '01.01.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 13, 'Джефф Хендрик', '31.01.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Нападающие', 14, 'Джонатан Уолтерс', '20.09.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Защитники', 15, 'Сайрус Кристи', '30.09.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Вратари', 16, 'Шэй Гивен', '20.04.76');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Защитники', 17, 'Стивен Уорд', '20.08.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 18, 'Дэвид Мейлер', '29.05.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 19, 'Роберт Брэди', '14.01.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 20, 'Уэсли Хулахан', '20.05.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Нападающие', 21, 'Дэрил Мерфи', '15.03.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Полузащитники', 22, 'Стивен Куинн', '01.04.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('ирландия', 'Вратари', 23, 'Даррен Рэндолф', '12.05.87');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Вратари', 1, 'Ханнес Халльдоурссон', '27.04.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 2, 'Биркир Севарссон', '11.11.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 3, 'Хаукур-Хейдар Хаукссон', '01.09.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 4, 'Йортюр Херманнссон', '08.02.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 5, 'Сверрир Ингасон', '05.08.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 6, 'Рагнар Сигурдссон', '19.06.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Нападающие', 7, 'Йохан Гудмундссон', '27.10.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Полузащитники', 8, 'Биркир Бьярнасон', '27.05.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Нападающие', 9, 'Колбейнн Сигторссон', '14.03.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Полузащитники', 10, 'Гильфи Сигурдссон', '08.09.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Нападающие', 11, 'Альфред Финнбогасон', '01.02.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Вратари', 12, 'Эгмундур Кристинссон', '19.06.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Вратари', 13, 'Ингвар Йонссон', '18.10.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Полузащитники', 14, 'Кари Арнасон', '13.10.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Нападающие', 15, 'Йон Бедварссон', '25.05.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Полузащитники', 16, 'Рунар Мар Сигурьонссон', '18.06.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Полузащитники', 17, 'Арон Гуннарссон', '22.04.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 18, 'Теодор Бьярнасон', '04.03.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 19, 'Хордур Магнуссон', '11.02.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Полузащитники', 20, 'Эмиль Хадльфредссон', '29.06.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 21, 'Арнор Траустасон', '30.04.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Нападающие', 22, 'Эйдур Гудьонсен', '15.09.78');
insert into t_player_buf(country, player_type, num, name, birthday) values('исландия', 'Защитники', 23, 'Ари Скуласон', '14.05.87');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Вратари', 1, 'Икер Касильяс', '20.05.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 2, 'Сесар Аспиликуэта', '28.08.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 3, 'Жерар Пике', '02.02.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 4, 'Марк Бартра', '15.01.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Полузащитники', 5, 'Серхио Бускетс', '16.07.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Полузащитники', 6, 'Андрес Иньеста', '11.05.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Нападающие', 7, 'Альваро Мората', '23.10.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Полузащитники', 8, 'Коке', '08.01.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Нападающие', 9, 'Лукас Васкес', '01.07.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Полузащитники', 10, 'Сеск Фабрегас', '04.05.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Нападающие', 11, 'Педро Родригес', '28.07.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 12, 'Эктор Бельерин', '19.03.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Вратари', 13, 'Давид де Хеа', '07.11.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Полузащитники', 14, 'Тьяго Алькантара', '11.04.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 15, 'Серхио Рамос', '30.03.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 16, 'Хуанфран', '09.01.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 17, 'Микель Сан-Хосе', '30.05.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Защитники', 18, 'Жорди Альба', '21.03.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Полузащитники', 19, 'Бруно Сориано', '12.06.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Нападающие', 20, 'Ариц Адурис', '11.02.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Полузащитники', 21, 'Давид Сильва', '08.01.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Нападающие', 22, 'Нолито', '15.10.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('испания', 'Вратари', 23, 'Серхио Рико', '01.09.93');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Вратари', 1, 'Джанлуиджи Буффон', '28.01.78');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Защитники', 2, 'Маттиа Де Шильо', '20.10.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Защитники', 3, 'Джорджио Кьеллини', '14.08.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Защитники', 4, 'Маттео Дармиан', '02.12.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Защитники', 5, 'Анджело Огбонна', '23.05.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 6, 'Антонио Кандрева', '28.02.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Нападающие', 7, 'Симоне Дзадза', '25.06.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 8, 'Алессандро Флоренци', '11.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Нападающие', 9, 'Грациано Пелле', '15.07.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 10, 'Тьяго Мотта', '28.08.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Нападающие', 11, 'Чиро Иммобиле', '20.02.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Вратари', 12, 'Сальваторе Сиригу', '12.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Вратари', 13, 'Федерико Маркетти', '07.02.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 14, 'Стефано Стураро', '09.03.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Защитники', 15, 'Андреа Бардзальи', '08.05.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 16, 'Даниэле Де Росси', '24.07.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Нападающие', 17, 'Эдер', '15.11.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 18, 'Марко Пароло', '25.01.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Защитники', 19, 'Леонардо Бонуччи', '01.05.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Нападающие', 20, 'Лоренцо Инсинье', '04.06.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 21, 'Федерико Бернардески', '16.02.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Нападающие', 22, 'Стефан Эль-Шаарави', '27.10.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('италия', 'Полузащитники', 23, 'Эмануэле Джаккерини', '05.05.85');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Вратари', 1, 'Войцех Щесны', '18.04.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Защитники', 2, 'Михал Паздан', '21.09.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Защитники', 3, 'Артур Енджейчик', '04.11.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Защитники', 4, 'Тяго Ционек', '21.04.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 5, 'Кжиштоф Мончиньски', '23.05.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 6, 'Томаш Йодловец', '08.09.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Нападающие', 7, 'Аркадиуш Милик', '28.02.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 8, 'Кароль Линетты', '02.02.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Нападающие', 9, 'Роберт Левандовски', '21.08.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 10, 'Гжегож Крыховяк', '29.01.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 11, 'Камиль Гросицки', '08.06.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Вратари', 12, 'Артур Боруц', '20.02.80');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Нападающие', 13, 'Мариуш Стемпиньски', '12.05.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Защитники', 14, 'Якуб Вавжиняк', '07.07.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Защитники', 15, 'Камиль Глик', '03.02.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 16, 'Якуб Блащиковски', '14.12.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 17, 'Славомир Пешко', '19.02.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Защитники', 18, 'Бартош Салямон', '01.05.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 19, 'Петр Зелиньски', '20.05.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Защитники', 20, 'Лукаш Пищек', '03.06.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 21, 'Бартош Капустка', '23.12.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Вратари', 22, 'Лукаш Фабяньски', '18.04.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('польша', 'Полузащитники', 23, 'Филип Стажиньски', '27.05.91');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Вратари', 1, 'Руй Патрисиу', '15.02.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Защитники', 2, 'Бруну Алвеш', '27.11.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Защитники', 3, 'Пепе', '26.02.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Защитники', 4, 'Жозе Фонте', '22.12.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Защитники', 5, 'Рафаэл Геррейру', '22.12.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Защитники', 6, 'Рикарду Карвалью', '18.05.78');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Нападающие', 7, 'Криштиану Роналду', '05.02.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 8, 'Жоау Моутинью', '08.09.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Нападающие', 9, 'Эдер', '22.12.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 10, 'Жоау Мариу', '19.01.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 11, 'Виейринья', '24.01.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Вратари', 12, 'Антони Лопеш', '01.10.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 13, 'Данилу', '09.09.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 14, 'Вилльям Карвалью', '07.04.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 15, 'Андре Гомеш', '30.07.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 16, 'Ренату Саншеш', '18.08.97');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Нападающие', 17, 'Нани', '17.11.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 18, 'Рафа Силва', '17.05.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Защитники', 19, 'Элизеу', '01.10.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Нападающие', 20, 'Рикарду Куарежма', '26.09.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Защитники', 21, 'Седрик', '31.08.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Вратари', 22, 'Эдуарду', '19.09.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('португалия', 'Полузащитники', 23, 'Адриен Силва', '15.03.89');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Вратари', 1, 'Игорь Акинфеев', '08.04.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 2, 'Роман Шишкин', '27.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 3, 'Игорь Смольников', '08.08.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 4, 'Сергей Игнашевич', '14.07.79');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 5, 'Роман Нойштедтер', '18.02.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 6, 'Алексей Березуцкий', '20.06.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 7, 'Игорь Денисов', '17.05.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 8, 'Денис Глушаков', '27.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Нападающие', 9, 'Александр Кокорин', '19.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Нападающие', 10, 'Федор Смолов', '09.02.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 11, 'Павел Мамаев', '17.09.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Вратари', 12, 'Юрий Лодыгин', '26.05.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 13, 'Александр Головин', '30.05.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 14, 'Василий Березуцкий', '20.06.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 15, 'Роман Широков', '06.07.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Вратари', 16, 'Маринато Гилерме', '12.12.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 17, 'Олег Шатов', '29.07.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 18, 'Олег Иванов', '04.08.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 19, 'Александр Самедов', '19.07.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Полузащитники', 20, 'Дмитрий Торбинский', '28.04.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 21, 'Георгий Щеннников', '27.04.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Нападающие', 22, 'Артем Дзюба', '22.08.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('россия', 'Защитники', 23, 'Дмитрий Комбаров', '22.01.87');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Вратари', 1, 'Костел Пантилимон', '01.02.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 2, 'Александру Мэцел', '17.10.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 3, 'Рэзван Рац', '26.05.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 4, 'Козмин Моци', '03.12.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 5, 'Овидиу Хобан', '27.12.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 6, 'Влад Кирикеш', '14.11.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 7, 'Александру Кипчу', '18.05.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 8, 'Михай Пантилий', '09.11.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Нападающие', 9, 'Денис Алибек', '05.01.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 10, 'Николае Станчу', '07.05.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 11, 'Габриэл Торже', '22.11.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Вратари', 12, 'Чиприан Тэтэрушану', '09.02.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Нападающие', 13, 'Клаудио Кешерю', '02.12.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Нападающие', 14, 'Флорин Андоне', '11.04.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 15, 'Валерикэ Гэман', '25.02.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 16, 'Стелиано Филип', '15.05.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 17, 'Лучан Сынмэртян', '13.03.80');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 18, 'Андрей Препелицэ', '08.12.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Нападающие', 19, 'Богдан Станку', '28.06.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Полузащитники', 20, 'Адриан Попа', '24.07.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 21, 'Драгош Григоре', '07.09.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Защитники', 22, 'Кристиан Сэпунару', '05.04.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('румыния', 'Вратари', 23, 'Силвиу Лунг', '04.06.89');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Вратари', 1, 'Майкл Макговерн', '12.07.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 2, 'Конор Маклафлин', '26.07.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Полузащитники', 3, 'Шейн Фергюсон', '12.07.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 4, 'Гарет Макаули', '05.12.79');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 5, 'Джонни Эванс', '03.01.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 6, 'Крис Бейрд', '25.02.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Нападающие', 7, 'Найал Макгинн', '20.07.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Полузащитники', 8, 'Стивен Дэвис', '01.01.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Нападающие', 9, 'Уилл Григг', '03.07.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Нападающие', 10, 'Кайл Лафферти', '16.09.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Нападающие', 11, 'Конор Вашингтон', '18.05.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Вратари', 12, 'Рой Кэрролл', '30.09.77');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Полузащитники', 13, 'Корри Эванс', '30.07.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Полузащитники', 14, 'Стюарт Даллас', '19.04.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 15, 'Люк Маккалох', '15.02.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Полузащитники', 16, 'Оливер Норвуд', '12.04.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 17, 'Пэдди Макнейр', '27.04.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 18, 'Арон Хьюз', '08.11.79');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Полузащитники', 19, 'Джейми Уорд', '12.05.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 20, 'Крэйг Кэткарт', '06.02.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Полузащитники', 21, 'Джош Мадженнис', '15.08.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Защитники', 22, 'Ли Ходсон', '02.10.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('северная ирландия', 'Вратари', 23, 'Алан Маннус', '19.05.82');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Вратари', 1, 'Ян Муха', '05.12.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 2, 'Петер Пекарик', '30.10.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 3, 'Мартин Шрктел', '15.12.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 4, 'Ян Дюрица', '10.12.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 5, 'Норберт Дьомбер', '03.07.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 6, 'Ян Грегуш', '29.01.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 7, 'Владимир Вайсс', '30.11.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 8, 'Ондрей Дуда', '05.12.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Нападающие', 9, 'Станислав Шестак', '16.12.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 10, 'Мирослав Стох', '19.10.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Нападающие', 11, 'Адам Немец', '02.09.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Вратари', 12, 'Ян Новота', '29.11.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 13, 'Патрик Грошовски', '22.04.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 14, 'Милан Шкриниар', '11.02.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 15, 'Томаш Губочан', '17.09.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 16, 'Корнел Салата', '24.01.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 17, 'Марек Гамшик', '27.07.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Защитники', 18, 'Душан Швенто', '01.08.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 19, 'Юрай Куцка', '26.02.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 20, 'Роберт Мак', '08.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Нападающие', 21, 'Михал Дюриш', '01.06.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Полузащитники', 22, 'Виктор Печовски', '24.05.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('словакия', 'Вратари', 23, 'Матуш Козачик', '27.12.83');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Вратари', 1, 'Волкан Бабаджан', '11.08.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Защитники', 2, 'Семих Кайя', '24.02.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Защитники', 3, 'Хакан Балта', '23.03.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Защитники', 4, 'Ахмет Чалык', '26.02.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 5, 'Нури Шахин', '05.09.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 6, 'Хакан Чалханоглу', '08.02.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Защитники', 7, 'Гекхан Генюл', '04.01.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 8, 'Сельчук Инан', '10.02.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Нападающие', 9, 'Дженк Тосун', '07.06.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 10, 'Арда Туран', '30.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 11, 'Олджай Шахан', '26.05.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Вратари', 12, 'Онур Кыврак', '01.01.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Защитники', 13, 'Исмаил Кейбаши', '10.07.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 14, 'Огузхан Эзьякуп', '23.09.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 15, 'Мехмет Топал', '03.03.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 16, 'Озан Туфан', '23.03.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Нападающие', 17, 'Бурак Йылмаз', '15.07.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 18, 'Джанер Эркин', '04.10.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 19, 'Юнус Маллы', '24.02.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Полузащитники', 20, 'Волкан Шен', '07.07.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Нападающие', 21, 'Эмре Мор', '24.07.97');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Защитники', 22, 'Шенер Эзбайраклы', '23.01.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('турция', 'Вратари', 23, 'Харун Текин', '17.06.89');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Вратари', 1, 'Денис Бойко', '29.01.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Защитники', 2, 'Богдан Бутко', '13.01.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Защитники', 3, 'Евгений Хачериди', '28.07.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 4, 'Анатолий Тимощук', '30.03.79');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Защитники', 5, 'Александр Кучер', '22.10.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 6, 'Тарас Степаненко', '08.08.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 7, 'Андрей Ярмоленко', '23.10.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Нападающие', 8, 'Роман Зозуля', '17.11.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 9, 'Виктор Коваленко', '14.02.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 10, 'Евгений Коноплянка', '29.09.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Нападающие', 11, 'Евгений Селезнев', '20.07.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Вратари', 12, 'Андрей Пятов', '28.06.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Защитники', 13, 'Вячеслав Шевчук', '13.05.79');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 14, 'Руслан Ротань', '29.10.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Нападающие', 15, 'Филипп Будковский', '10.03.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 16, 'Сергей Сидорчук', '02.05.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Защитники', 17, 'Артем Федецкий', '26.04.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 18, 'Сергей Рыбалка', '01.04.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 19, 'Денис Гармаш', '19.04.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Защитники', 20, 'Ярослав Ракицкий', '03.08.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 21, 'Александр Зинченко', '15.12.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Полузащитники', 22, 'Александр Караваев', '02.06.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('украина', 'Вратари', 23, 'Никита Шевченко', '26.01.93');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Вратари', 1, 'Уэйн Хеннесси', '24.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Защитники', 2, 'Кристофер Гантер', '21.07.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Защитники', 3, 'Нил Тейлор', '07.02.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Защитники', 4, 'Бен Дэвис', '24.04.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Защитники', 5, 'Джеймс Честер', '23.01.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Защитники', 6, 'Эшли Уильямс', '23.08.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 7, 'Джо Аллен', '14.03.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 8, 'Эндрю Кинг', '29.10.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 9, 'Хэл Робсон-Кану', '21.05.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 10, 'Арон Рэмзи', '26.12.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Нападающие', 11, 'Гарет Бэйл', '16.07.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Вратари', 12, 'Оуэйн Уильямс', '17.03.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Нападающие', 13, 'Джордж Уильямс', '07.09.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 14, 'Дэвид Эдвардс', '03.02.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Защитники', 15, 'Джэз Ричардс', '12.04.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 16, 'Джо Лэдли', '23.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Нападающие', 17, 'Дэвид Коттерилл', '04.12.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Нападающие', 18, 'Сэм Воукс', '21.10.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Защитники', 19, 'Джеймс Коллинз', '23.08.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 20, 'Джонатан Уильямс', '09.10.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Вратари', 21, 'Дэнни Уорд', '22.06.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Полузащитники', 22, 'Дэвид Воган', '18.02.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('уэльс', 'Нападающие', 23, 'Саймон Черч', '10.12.88');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Вратари', 1, 'Уго Льорис', '26.12.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 2, 'Кристоф Жалле', '31.10.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 3, 'Патрис Эвра', '15.05.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 4, 'Адиль Рами', '27.12.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 5, 'Нголо Канте', '29.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 6, 'Йоан Кабай', '14.01.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Нападающие', 7, 'Антуан Гризманн', '21.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 8, 'Димитри Пайе', '29.03.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Нападающие', 9, 'Оливье Жиру', '30.09.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Нападающие', 10, 'Андре-Пьер Жиньяк', '05.12.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Нападающие', 11, 'Антони Марсьяль', '05.12.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 12, 'Морган Шнедерлен', '08.11.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 13, 'Эльяким Мангаля', '13.02.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 14, 'Блез Матюиди', '09.04.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 15, 'Поль Погба', '15.03.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Вратари', 16, 'Стив Манданда', '28.03.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 17, 'Люка Динь', '20.07.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 18, 'Мусса Сиссоко', '16.08.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 19, 'Бакари Санья', '14.02.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Полузащитники', 20, 'Кингсли Коман', '13.06.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 21, 'Лоран Косельны', '10.09.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Защитники', 22, 'Самюэль Юмтити', '14.11.93');
insert into t_player_buf(country, player_type, num, name, birthday) values('франция', 'Вратари', 23, 'Бенуа Костиль', '03.07.87');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Вратари', 1, 'Иван Варгич', '15.03.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Защитники', 2, 'Шиме Врсалько', '10.01.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Защитники', 3, 'Иван Стринич', '17.07.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 4, 'Иван Перишич', '02.02.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Защитники', 5, 'Ведран Чорлука', '05.02.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Защитники', 6, 'Тин Едвай', '28.11.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 7, 'Иван Ракитич', '10.03.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 8, 'Матео Ковачич', '06.05.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Нападающие', 9, 'Андрей Крамарич', '19.06.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 10, 'Лука Модрич', '09.09.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Защитники', 11, 'Дарио Срна', '01.05.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Вратари', 12, 'Ловре Калинич', '03.04.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Защитники', 13, 'Гордон Шильденфельд', '18.03.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 14, 'Марцело Брозович', '16.11.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 15, 'Марко Рог', '19.07.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Нападающие', 16, 'Никола Калинич', '05.01.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Нападающие', 17, 'Марио Манджукич', '21.05.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 18, 'Анте Чорич', '14.04.97');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Полузащитники', 19, 'Милан Бадель', '25.02.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Нападающие', 20, 'Марко Пьяца', '06.05.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Защитники', 21, 'Домагой Вида', '29.04.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Нападающие', 22, 'Дуе Чоп', '01.02.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('хорватия', 'Вратари', 23, 'Даниель Субашич', '27.10.84');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Вратари', 1, 'Петр Чех', '20.05.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Защитники', 2, 'Павел Кадержабек', '25.04.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Защитники', 3, 'Михал Кадлец', '13.12.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Защитники', 4, 'Теодор Гебре Селассие', '24.12.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Защитники', 5, 'Роман Губник', '06.06.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Защитники', 6, 'Томаш Сивок', '15.09.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Нападающие', 7, 'Томаш Нецид', '13.08.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Защитники', 8, 'Давид Лимберски', '06.10.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 9, 'Боржек Дочкал', '30.09.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 10, 'Томаш Росицки', '04.10.80');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 11, 'Даниэл Пудил', '27.09.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Нападающие', 12, 'Милан Шкода', '16.01.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 13, 'Ярослав Плашил', '05.01.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 14, 'Даниэл Коларж', '27.10.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 15, 'Давид Павелка', '18.05.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Вратари', 16, 'Томаш Вацлик', '29.03.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Защитники', 17, 'Марек Сухи', '29.03.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 18, 'Йосеф Шурал', '30.05.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 19, 'Ладислав Крейчи', '05.07.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 20, 'Иржи Скалак', '12.03.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Нападающие', 21, 'Давид Лафата', '18.09.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Полузащитники', 22, 'Владимир Дарида', '08.08.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('чехия', 'Вратари', 23, 'Томаш Коубек', '26.08.92');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Вратари', 1, 'Ян Соммер', '17.12.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 2, 'Стефан Лихтштайнер', '16.01.84');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 3, 'Франсуа Мубандже', '21.06.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 4, 'Нико Эльведи', '30.09.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 5, 'Стив фон Берген', '10.06.83');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 6, 'Михаэль Ланг', '08.02.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Нападающие', 7, 'Брель Эмболо', '14.02.97');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Полузащитники', 8, 'Фабиан Фрай', '08.01.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Нападающие', 9, 'Харис Сеферович', '22.02.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Полузащитники', 10, 'Гранит Джака', '07.09.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Полузащитники', 11, 'Валон Бехрами', '19.04.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Вратари', 12, 'Марвин Хитц', '18.09.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 13, 'Рикардо Родригес', '25.08.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Полузащитники', 14, 'Денис Закария', '20.11.96');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Полузащитники', 15, 'Блерим Джемайли', '12.04.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Полузащитники', 16, 'Желсон Фернандес', '02.09.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Нападающие', 17, 'Шани Тарашай', '07.02.95');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Нападающие', 18, 'Адмир Мехмеди', '16.03.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Нападающие', 19, 'Эрен Дердийок', '12.06.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 20, 'Йохан Джуру', '18.01.87');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Вратари', 21, 'Роман Бюрки', '14.11.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Защитники', 22, 'Фабиан Шер', '20.12.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('швейцария', 'Полузащитники', 23, 'Джердан Шакири', '10.10.91');
commit;
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Вратари', 1, 'Андреас Исакссон', '03.10.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Защитники', 2, 'Микаэль Лустиг', '13.12.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Защитники', 3, 'Эрик Юханссон', '30.12.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Защитники', 4, 'Андреас Гранквист', '16.04.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Защитники', 5, 'Мартин Ольссон', '17.05.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 6, 'Эмиль Форсберг', '23.10.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 7, 'Себастьян Ларссон', '06.06.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 8, 'Альбин Экдаль', '28.07.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 9, 'Ким Чельстрем', '24.08.82');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Нападающие', 10, 'Златан Ибрагимович', '03.10.81');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Нападающие', 11, 'Маркус Берг', '17.08.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Вратари', 12, 'Робин Ольсен', '08.01.90');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Защитники', 13, 'Понтус Янссон', '13.02.91');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Защитники', 14, 'Виктор Линделеф', '17.07.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 15, 'Оскар Хильемарк', '28.06.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 16, 'Понтус Вернблум', '25.06.86');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Защитники', 17, 'Людвиг Аугустинссон', '21.04.94');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 18, 'Оскар Левицки', '14.07.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Нападающие', 19, 'Эмир Куйович', '22.06.88');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Нападающие', 20, 'Йон Гвидетти', '15.04.92');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 21, 'Джимми Дурмаз', '22.03.89');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Полузащитники', 22, 'Эркан Зенгин', '05.08.85');
insert into t_player_buf(country, player_type, num, name, birthday) values('швеция', 'Вратари', 23, 'Патрик Карлгрен', '08.01.92');
commit;
